### ISSUE TITLE
No Respon

### ISSUE THREAD

**Issue by masadi** [tegohsx/laporan-keuangan-bot#2]
![image](https://user-images.githubusercontent.com/5530849/183976697-93af4656-41e6-484c-b578-a3049e4fb7fa.png)
![image](https://user-images.githubusercontent.com/5530849/183976753-7fd63c00-ddc9-4929-b5fd-72eb4df743d9.png)

**Comment by tegohsx** [comment]
Pastikan saat deploy set akses anyone

**Comment by masadi** [comment]
@masadi udah om, anyone dan akses editor juga

**Comment by zafranf** [comment]
nama sheetnya diubah coba om, gak bisa default Sheet1..saya no respon juga pas Sheet1, setelah rename langsung bisa..
