### ISSUE TITLE
Bot No Respon

### ISSUE THREAD

**Issue by eduardusguntur** [tegohsx/laporan-keuangan-bot#6]
Webhook sudah berhasil diset
![image](https://user-images.githubusercontent.com/109570521/192421373-b08b2f68-a5ea-4273-89dc-840c5e750e4d.png)
namun saat trial coba data /new,
Bot no Respons
![image](https://user-images.githubusercontent.com/109570521/192421269-8e7ebe35-1d36-49dc-aec5-1514cec1d7f3.png)
sudah coba buat 2 bot dan 2 spreadsheet yang berbeda, namun tetap no respon..
mohon bantuan nya mas Teguh

nb. saya ada chat via telegram juga ke mas Teguh..
Terima kasih mas

**Comment by eduardusguntur** [comment]
terdapat response balikan, namun hanya yang else nya saja atau Response Gagal nya saja
![image](https://user-images.githubusercontent.com/109570521/192431408-467eca47-4ee0-4418-9deb-53119d266412.png)

**Comment by tegohsx** [comment]
pastikan nama sheet sesuai dan driver.gs telah dibuat
